spring:
  r2dbc:
    url: ${SPRING_R2DBC_URL}
    username: ${SPRING_R2DBC_USERNAME}
    password: ${SPRING_R2DBC_PASSWORD}

  sql:
    init:
      mode: never

server:
  port: 8080
  # ssl:
  #   key-store: classpath:keystore.p12
  #   key-store-password: franquicias123
  #   key-store-type: PKCS12
  #   key-alias: franquicias

springdoc:
  swagger-ui:
    path: /swagger-ui.html